/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controler.ManageTestDetails;
import controler.MessageManagement;
import controler.Validations;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Objects;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Test;

/**
 *
 * @author lihin
 */
@SuppressWarnings("serial")
public class LabDataEntryForm extends javax.swing.JFrame {

    /**
     * Creates new form LabDataEntryForm
     */
    public LabDataEntryForm() {
        initComponents();
        this.setTitle("INSERT FORM");
        loadTests();
        timeUpdate();
    }

    void refreashTable() {
        Thread time;
        Thread t = new Thread() {
            @Override
            public void run() {
                if (txtSearch.getText().length() == 0) {
                    try {
                        loadTests();
                        Thread.sleep(20000000);
                    } catch (InterruptedException e) {
                    } catch (Exception e) {
                    }
                }
            }

        };
        time = new Thread() {
            @Override
            public void run() {
                while (true) {
                    if (txtSearch.getText().length() == 0) {

                        try {
                            loadTests();
                            Thread.sleep(20000000);

                        } catch (InterruptedException e) {
                        } catch (Exception e) {
                        }
                    }
                }
            }

        };
        t.start();
    }

    final void timeUpdate() {

        Thread time;
        time = new Thread() {
            @Override
            public void run() {

                while (true) {

                    try {
                        LocalDateTime datetime = LocalDateTime.now();
                        DateTimeFormatter dateTimeFormat = DateTimeFormatter.ofPattern("dd-MM-yyyy  HH:mm:ss");
                        String dateTime = datetime.format(dateTimeFormat);
                        lblDateTime.setText(dateTime);

                        Thread.sleep(1000);
                    } catch (InterruptedException e) {
                    } catch (Exception e) {
                    }
                }
            }
        };
        time.start();

    }

    @SuppressWarnings("unchecked")
    final void loadTests() {
        try {
            ManageTestDetails test = new ManageTestDetails();
            ResultSet result = test.loadTest();
            ((DefaultTableModel) tblTestInfo.getModel()).setNumRows(0);
            DefaultTableModel model = (DefaultTableModel) tblTestInfo.getModel();
            //System.out.println(result.getString("vname"));

            while (result.next()) {
                Vector vec = new Vector();
                vec.add(result.getString("sampleid"));//1
                vec.add(result.getString("date"));//2
                vec.add(result.getString("status"));//3
                vec.add(result.getString("vid"));//4
                vec.add(result.getString("vtel"));//5
                vec.add(result.getString("vname"));//6
                vec.add(result.getString("vgender"));//7
                vec.add(result.getInt("vage"));//7
                vec.add(result.getString("vaddres"));//8
                vec.add(result.getString("Province"));//9
                vec.add(result.getString("District"));//10

                model.addRow(vec);

            }

            tblTestInfo.setModel(model);
        } catch (SQLException e) {

        } catch (ArrayIndexOutOfBoundsException e) {

        } catch (Exception e) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupGender = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblDateTime = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtNic = new javax.swing.JTextField();
        rbtnMale = new javax.swing.JRadioButton();
        rbtnFemale = new javax.swing.JRadioButton();
        spnAge = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        txtSampleId = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cmbResult = new javax.swing.JComboBox<>();
        btnClear = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        cmbProvince = new javax.swing.JComboBox<>();
        lblErr = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lblDistrict = new javax.swing.JLabel();
        cmbDistrict = new javax.swing.JComboBox<>();
        btnInsert = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblSearch = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTestInfo = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jPanel4.setBackground(new java.awt.Color(0, 51, 51));

        lblDateTime.setForeground(new java.awt.Color(255, 255, 255));
        lblDateTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDateTime.setText("jLabel3");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(1350, Short.MAX_VALUE)
                .addComponent(lblDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDateTime))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 0));
        jPanel2.setOpaque(false);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name                      :");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NIC  No                   :");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Gender                    :");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Age                          :");

        rbtnMale.setBackground(new java.awt.Color(102, 102, 102));
        btnGroupGender.add(rbtnMale);
        rbtnMale.setText("Male");

        rbtnFemale.setBackground(new java.awt.Color(102, 102, 102));
        btnGroupGender.add(rbtnFemale);
        rbtnFemale.setText("Female");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Telephone No        :");

        txtContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Province                 :");

        jPanel5.setOpaque(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Address            :");

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        jScrollPane2.setViewportView(txtAddress);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Sample ID        :");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Result         :");

        cmbResult.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not Tested", "Negative", "Possitive" }));

        btnClear.setBackground(new java.awt.Color(221, 160, 221));
        btnClear.setForeground(new java.awt.Color(0, 0, 0));
        btnClear.setText("Clear");
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(240, 128, 128));
        btnDelete.setForeground(new java.awt.Color(0, 0, 0));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(102, 205, 170));
        btnUpdate.setForeground(new java.awt.Color(0, 0, 0));
        btnUpdate.setText("Update");
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });

        cmbProvince.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Northern", "NorthWestern", "Western", "NorthCentral", "Central", "Sabaragamuwa\t", "Eastern", "Uva", "Southern", " " }));
        cmbProvince.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmbProvinceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmbProvinceFocusLost(evt);
            }
        });

        lblErr.setForeground(new java.awt.Color(153, 0, 0));

        jPanel6.setOpaque(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblDistrict.setForeground(new java.awt.Color(255, 255, 255));
        lblDistrict.setText("District                    :");

        cmbDistrict.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        cmbDistrict.setToolTipText("Select Province to get Districts");
        cmbDistrict.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmbDistrictFocusGained(evt);
            }
        });

        btnInsert.setBackground(new java.awt.Color(0, 191, 255));
        btnInsert.setForeground(new java.awt.Color(0, 0, 0));
        btnInsert.setText("Insert");
        btnInsert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInsertMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDistrict, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                        .addComponent(txtNic))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cmbProvince, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(rbtnMale, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(rbtnFemale))
                        .addComponent(spnAge))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cmbDistrict, javax.swing.GroupLayout.Alignment.LEADING, 0, 217, Short.MAX_VALUE)
                        .addComponent(txtContact, javax.swing.GroupLayout.Alignment.LEADING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtSampleId, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbResult, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblErr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(497, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(rbtnMale)
                            .addComponent(rbtnFemale))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(spnAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cmbProvince, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDistrict)
                            .addComponent(cmbDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(9, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtSampleId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(cmbResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnInsert)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblErr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete)
                        .addGap(18, 18, 18)
                        .addComponent(btnClear)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate)
                        .addGap(66, 66, 66))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSearch.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblSearch.setForeground(new java.awt.Color(255, 255, 255));
        lblSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSearch.setText("Search :");
        jPanel3.add(lblSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 150, -1));

        txtSearch.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        txtSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtSearchMouseReleased(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        jPanel3.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 280, -1));

        jScrollPane1.setBackground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setOpaque(false);

        tblTestInfo.setBackground(new java.awt.Color(51, 51, 51));
        tblTestInfo.setForeground(new java.awt.Color(204, 204, 204));
        tblTestInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Test ID", "Test Date", "Result", "Patient NIC", "Patient Contac No.", "Patient Name", "Gender", "Age", "Address", "Province", "District"
            }
        ));
        tblTestInfo.setColumnSelectionAllowed(true);
        tblTestInfo.setOpaque(false);
        jScrollPane1.setViewportView(tblTestInfo);
        tblTestInfo.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(111, 111, 111))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        ManageTestDetails test = new ManageTestDetails();

        if (txtSampleId.getText().length() == 0) {
            JOptionPane.showMessageDialog(MessageManagement.getVisibleContent(), "Enter the Sample Id(Test Id) \nYou want to Delete", "Data Management ", JOptionPane.INFORMATION_MESSAGE);
        } else {

            if (test.checkSampleId(txtSampleId.getText())) {

                if (test.deletRecord(txtSampleId.getText())) {
                    JOptionPane.showMessageDialog(MessageManagement.getVisibleContent(), "Record Deleted Successfully ", "Data Management ", JOptionPane.INFORMATION_MESSAGE);
                    refreashTable();
                } else {
                    JOptionPane.showMessageDialog(MessageManagement.getVisibleContent(), "Record Delete Failed ", "Data Management ", JOptionPane.INFORMATION_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(MessageManagement.getVisibleContent(), "Invalid Sample Id\nMake sure you are Deleting an Exhisting record.", "Data Management ", JOptionPane.INFORMATION_MESSAGE);
            }
        }


    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnInsertMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertMouseClicked
        // TODO add your handling code here:

        {
            // TODO add your handling code here:

            String gender;

            if (txtName.getText().length() == 0) {
                lblErr.setText("*Name is Empty!!");
            } else if (Validations.validateNoNumSymb(txtName.getText())) {
                lblErr.setText("*Name Can not Contain Symbols or Numbers");
            } else if (txtNic.getText().length() == 0) {

            } else if (Validations.validateNoSpace(txtNic.getText())) {
                lblErr.setText("*Id can not contain spaces!");

                if ("Underage".equals(txtNic.getText()) || "underage".equals(txtNic.getText())) {
                    lblErr.setText("");
                } else {
                    lblErr.setText("*Id Cannot be Blank!! ");
                    JOptionPane.showMessageDialog(MessageManagement.getVisibleContent(), "If the person is uderaged,\nType 'Underage' or 'underage' with no spacecs ", "Test Details Management", JOptionPane.INFORMATION_MESSAGE);
                }
            } else if (Objects.equals(Validations.validateOldId(txtNic.getText()), Validations.validateNewId(txtNic.getText()))) {

                if ("Underage".equals(txtNic.getText()) || "underage".equals(txtNic.getText())) {
                    lblErr.setText("");
                } else {
                    lblErr.setText("*Invalid ID!! ");
                    JOptionPane.showMessageDialog(MessageManagement.getVisibleContent(), "If the person is uderaged,\nType 'Underage' or 'underage' with no spacecs ", "Test Details Management", JOptionPane.INFORMATION_MESSAGE);
                }
            } else if (btnGroupGender.getSelection() == null) {
                lblErr.setText("*Select Gender");
            } else if (!Validations.validateOnlyNum(spnAge.getValue().toString())) {
                lblErr.setText("*Age should be numeric");
            } else if (spnAge.getValue().toString().length() > 2) {
                lblErr.setText("*Invalid Age");
            } else if (Validations.validateContact(txtContact.getText())) {
                lblErr.setText("*Invalid mobile No");
            } else if (cmbProvince.getSelectedIndex() == 0) {
                lblErr.setText("*Select Province");
            } else if (cmbDistrict.getSelectedIndex() == 0) {
                lblErr.setText("*Select District");
            } else if (txtAddress.getText().length() == 0) {
                lblErr.setText("*Address is required");
            } else if (txtSampleId.getText().length() == 0) {
                lblErr.setText("*Sample ID is required");
            } else {
                lblErr.setText("");
            }
            if (rbtnMale.isSelected()) {
                gender = "male";
            } else {
                gender = "female";
            }
            if (lblErr.getText().length() == 0) {
                Test test = new Test(txtSampleId.getText(), txtName.getText(), txtNic.getText(), gender, (Integer) spnAge.getValue(), txtContact.getText(), txtAddress.getText(), (String) cmbResult.getSelectedItem(), (String) cmbProvince.getSelectedItem(), (String) cmbDistrict.getSelectedItem());
                ManageTestDetails saveTest = new ManageTestDetails(test);
                saveTest.saveTest();

                loadTests();
            }

            /* Test test =new Test(txtName.getText(),txtId.getText(),(Integer)txtAge.getValue(),txtTelno.getText(),txtAddr.getText()); 
        ManageTest saveTest = new ManageTest(test);
        saveTest.saveTest();*/
        }


    }//GEN-LAST:event_btnInsertMouseClicked

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        // TODO add your handling code here:
        ManageTestDetails test = new ManageTestDetails();
        boolean i;
        if (txtSampleId.getText().length() == 0) {
            JOptionPane.showMessageDialog(MessageManagement.getVisibleContent(), "Enter the Sample Id(Test Id) \nYou want to Update", "Data Management ", JOptionPane.INFORMATION_MESSAGE);
        } else {
            i = test.checkSampleId(txtSampleId.getText());
            if (i) {

                i = test.updateResults(txtSampleId.getText(), (String) cmbResult.getSelectedItem());
                if (i) {
                    JOptionPane.showMessageDialog(MessageManagement.getVisibleContent(), "Results Updated Successfully ", "Data Management ", JOptionPane.INFORMATION_MESSAGE);
                    refreashTable();
                } else {
                    JOptionPane.showMessageDialog(MessageManagement.getVisibleContent(), " Results Update Failed ", "Data Management ", JOptionPane.INFORMATION_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(MessageManagement.getVisibleContent(), "Invalid Test Id\nMake sure you are entering results to an Exhisting record.\nIf not please use 'Insert' option ", "Data Management ", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnUpdateMouseClicked

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        // TODO add your handling code here:
        txtName.setText(null);
        txtNic.setText(null);
        spnAge.setValue(0);
        txtContact.setText(null);
        txtAddress.setText(null);
        txtSampleId.setText(null);
        btnGroupGender.clearSelection();
        cmbProvince.setSelectedIndex(0);
        cmbDistrict.setSelectedIndex(0);
        cmbResult.setSelectedIndex(0);
        lblErr.setText("");

    }//GEN-LAST:event_btnClearMouseClicked

    @SuppressWarnings("unchecked")
    private void txtSearchMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchMouseReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_txtSearchMouseReleased

    @SuppressWarnings("unchecked")
    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:

        try {

            ManageTestDetails test = new ManageTestDetails();
            ResultSet result = test.loadTestbyID(txtSearch.getText());
            ((DefaultTableModel) tblTestInfo.getModel()).setNumRows(0);
            DefaultTableModel model = (DefaultTableModel) tblTestInfo.getModel();
            //System.out.println(result.getString("vname"));

            while (result.next()) {
                Vector vec = new Vector();
                vec.add(result.getString("sampleid"));//1
                vec.add(result.getString("date"));//2
                vec.add(result.getString("status"));//3
                vec.add(result.getString("vid"));//4
                vec.add(result.getString("vtel"));//5
                vec.add(result.getString("vname"));//6
                vec.add(result.getString("vgender"));//7
                vec.add(result.getInt("vage"));//7
                vec.add(result.getString("vaddres"));//8
                vec.add(result.getString("Province"));//9
                vec.add(result.getString("District"));//10
                model.addRow(vec);

            }

            refreashTable();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(MessageManagement.getVisibleContent(), "Data Transit Failed \n\r" + e.getClass() + "\n\r" + e.getMessage(), "Test Details Management", JOptionPane.INFORMATION_MESSAGE);

        } catch (ArrayIndexOutOfBoundsException e) {

        } catch (Exception e) {
            JOptionPane.showMessageDialog(MessageManagement.getVisibleContent(), "Data Transit Failed \n\r" + e.getClass() + "\n\r" + e.getMessage(), "Test Details Management", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_txtSearchKeyReleased

    @SuppressWarnings("deprecation")
    private void cmbProvinceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbProvinceFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbProvinceFocusLost

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        cmbDistrict.addItem("Select");
        cmbDistrict.setSelectedItem("Select");
    }//GEN-LAST:event_formWindowOpened

    private void cmbProvinceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbProvinceFocusGained
        // TODO add your handling code here:
        cmbDistrict.removeAllItems();
        cmbDistrict.addItem("Select");
        cmbDistrict.setSelectedIndex(0);
    }//GEN-LAST:event_cmbProvinceFocusGained

    private void cmbDistrictFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbDistrictFocusGained
        // TODO add your handling code here:
        cmbDistrict.removeAllItems();

        if (cmbProvince.getSelectedItem() == "Northern") {
            cmbDistrict.addItem("Select");
            cmbDistrict.addItem("Jaffna");
            cmbDistrict.addItem("Kilinochchi");
            cmbDistrict.addItem("Mannar");
            cmbDistrict.addItem("Mullaitivu");
            cmbDistrict.addItem("Vavuniya");
            cmbDistrict.setSelectedItem("Select");

        } else if (cmbProvince.getSelectedItem() == "NorthWestern") {
            cmbDistrict.addItem("Select");
            cmbDistrict.addItem("Puttalam");
            cmbDistrict.addItem("Kurunegala");
            cmbDistrict.setSelectedItem("Select");

        } else if (cmbProvince.getSelectedItem() == "Western") {
            cmbDistrict.addItem("Select");
            cmbDistrict.addItem("Gampaha");
            cmbDistrict.addItem("Colombo");
            cmbDistrict.addItem("Colombo");
            cmbDistrict.setSelectedItem("Select");

        } else if (cmbProvince.getSelectedItem() == "NorthCentral") {
            cmbDistrict.addItem("Select");
            cmbDistrict.addItem("Anuradhapura");
            cmbDistrict.addItem("Polonnaruwa");
            cmbDistrict.setSelectedItem("Select");

        } else if (cmbProvince.getSelectedItem() == "Central") {
            cmbDistrict.addItem("Select");
            cmbDistrict.addItem("Matale");
            cmbDistrict.addItem("Kandy");
            cmbDistrict.addItem("Nuwara Eliya");
            cmbDistrict.setSelectedItem("Select");

        } else if (cmbProvince.getSelectedItem() == "Sabaragamuwa	") {
            cmbDistrict.addItem("Select");
            cmbDistrict.addItem("Kegalle");
            cmbDistrict.addItem("Ratnapura");
            cmbDistrict.setSelectedItem("Select");

        } else if (cmbProvince.getSelectedItem() == "Eastern") {
            cmbDistrict.addItem("Select");
            cmbDistrict.addItem("Trincomalee");
            cmbDistrict.addItem("Batticaloa");
            cmbDistrict.addItem("Ampara");
            cmbDistrict.setSelectedItem("Select");

        } else if (cmbProvince.getSelectedItem() == "Uva") {
            cmbDistrict.addItem("Select");
            cmbDistrict.addItem("Badulla");
            cmbDistrict.addItem("Monaragala");
            cmbDistrict.setSelectedItem("Select");

        } else if (cmbProvince.getSelectedItem() == "Southern") {
            cmbDistrict.addItem("Select");
            cmbDistrict.addItem("Hambantota");
            cmbDistrict.addItem("Matara");
            cmbDistrict.addItem("Galle");
            cmbDistrict.setSelectedItem("Select");

        } else {
            cmbDistrict.addItem("Select");
            cmbDistrict.setSelectedItem("Select");
        }

    }//GEN-LAST:event_cmbDistrictFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LabDataEntryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LabDataEntryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LabDataEntryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LabDataEntryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LabDataEntryForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.ButtonGroup btnGroupGender;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbDistrict;
    private javax.swing.JComboBox<String> cmbProvince;
    private javax.swing.JComboBox<String> cmbResult;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDateTime;
    private javax.swing.JLabel lblDistrict;
    private javax.swing.JLabel lblErr;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JRadioButton rbtnFemale;
    private javax.swing.JRadioButton rbtnMale;
    private javax.swing.JSpinner spnAge;
    private javax.swing.JTable tblTestInfo;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNic;
    private javax.swing.JTextField txtSampleId;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
