/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controler.ManageReports;
import controler.MessageManagement;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/**
 *
 * @author lihin
 */
public class SelectDateRange extends javax.swing.JDialog {

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;

    /**
     * Creates new form SelectDateRange
     */
    public SelectDateRange(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("SELECT DATE RANGE");

        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        cmbProvince = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbDistrict = new javax.swing.JComboBox<>();
        cmbResult = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        dcDate = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        cmbProvince.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Any", "Northern", "NorthWestern", "Western", "NorthCentral", "Central", "Sabaragamuwa\t", "Eastern", "Uva", "Southern" }));
        cmbProvince.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmbProvinceFocusLost(evt);
            }
        });
        cmbProvince.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProvinceActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Province                    :");

        cmbDistrict.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Any" }));
        cmbDistrict.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmbDistrictFocusGained(evt);
            }
        });

        cmbResult.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Any", "Possitive", "Negative", "Not Tested" }));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Result                         :");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Date                           :");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("District                       :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dcDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbResult, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbProvince, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbDistrict, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(cancelButton)))
                .addGap(151, 151, 151))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, okButton});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dcDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbProvince, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addContainerGap(184, Short.MAX_VALUE))
        );

        getRootPane().setDefaultButton(okButton);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed

        String sql = null;
        int province = 1;
        int distric = 1;
        int result = 1;

        try {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date = sdf.format(dcDate.getDate());

            if (cmbProvince.getSelectedIndex() == 0) {
                province = 0;
            }
            if (cmbDistrict.getSelectedIndex() == 0) {
                distric = 0;
            }
            if (cmbResult.getSelectedIndex() == 0) {
                result = 0;
            }

            
            if (province == 0 && distric == 0 && result == 0) {

                sql = "SELECT * FROM tbl_testinfo WHERE date LIKE '" + date + "%'";
            } else if (province == 0 && distric == 0 && result == 1) {

                sql = "SELECT * FROM tbl_testinfo WHERE date LIKE '" + date + "%' AND status ='" + cmbResult.getSelectedItem() + "'";
            } else if (province == 1 && distric == 0 && result == 0) {

                sql = "SELECT * FROM tbl_testinfo WHERE date LIKE '" + date + "%' AND Province ='" + cmbProvince.getSelectedItem() + "'";
            } else if (province == 1 && distric == 0 && result == 1) {

                sql = "SELECT * FROM tbl_testinfo WHERE date LIKE '" + date + "%' AND Province ='" + cmbProvince.getSelectedItem() + "' AND result ='" + cmbResult.getSelectedItem() + "'";
            }/*else if( province==1 &&  distric==0 && result == 1){
            
               sql="SELECT * FROM tbl_testinfo WHERE date LIKE '"+date+"%' AND Province ='"+cmbProvince.getSelectedItem()+"' AND result ='"+cmbResult.getSelectedItem()+"'";
            }*/ else if (province == 1 && distric == 1 && result == 0) {

                sql = "SELECT * FROM tbl_testinfo WHERE date LIKE '" + date + "%' AND Province ='" + cmbProvince.getSelectedItem() + "' AND District ='" + cmbDistrict.getSelectedItem() + "'";
            } else if (province == 1 && distric == 1 && result == 1) {

                sql = "SELECT* FROM tbl_testinfo WHERE date LIKE '" + date + "%' AND Province ='" + cmbProvince.getSelectedItem() + "' AND District ='" + cmbDistrict.getSelectedItem() + "' And result ='" + cmbResult.getSelectedItem() + "'";
            }
            if (!(sql.isEmpty())) {
                String design = "E:\\EAD CW2 CODSE201f-038\\EAD_CW_2-pcr management system\\src\\Reports\\TemplateForMultipleTests.jrxml";
                try {
                    ManageReports.genarateReports(sql,design);
                     doClose(RET_OK);
                } catch (Exception ex) {
                    Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
              
        } catch (HeadlessException headlessException) {

        } catch (NullPointerException e) {

            JOptionPane.showMessageDialog(MessageManagement.getVisibleContent(), " Select Date ", "Report Management ", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {

            JOptionPane.showMessageDialog(MessageManagement.getVisibleContent(), "Data Transit Failed \n\r" + e.getClass() + "\n\r" + e.getMessage(), "Test Details Management", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void cmbProvinceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProvinceActionPerformed
        // TODO add your handling code here:
        cmbDistrict.removeAllItems();
        cmbDistrict.addItem("Any");
        cmbDistrict.setSelectedIndex(0);


    }//GEN-LAST:event_cmbProvinceActionPerformed

    private void cmbDistrictFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbDistrictFocusGained
        // TODO add your handling code here:
        cmbDistrict.removeAllItems();
        cmbDistrict.addItem("Any");
       

        if (cmbProvince.getSelectedItem() == "Northern") {
            cmbDistrict.removeAllItems();
            cmbDistrict.addItem("Any");
            cmbDistrict.addItem("Jaffna");
            cmbDistrict.addItem("Kilinochchi");
            cmbDistrict.addItem("Mannar");
            cmbDistrict.addItem("Mullaitivu");
            cmbDistrict.addItem("Vavuniya");
            cmbDistrict.setSelectedIndex(0);

        } else if (cmbProvince.getSelectedItem() == "NorthWestern") {
            cmbDistrict.removeAllItems();
            cmbDistrict.addItem("Any");
            cmbDistrict.addItem("Puttalam");
            cmbDistrict.addItem("Kurunegala");
            cmbDistrict.setSelectedIndex(0);

        } else if (cmbProvince.getSelectedItem() == "Western") {
            cmbDistrict.removeAllItems();
            cmbDistrict.addItem("Any");
            cmbDistrict.addItem("Gampaha");
            cmbDistrict.addItem("Colombo");
            cmbDistrict.addItem("Colombo");
            cmbDistrict.setSelectedIndex(0);

        } else if (cmbProvince.getSelectedItem() == "NorthCentral") {
            cmbDistrict.removeAllItems();
            cmbDistrict.addItem("Any");
            cmbDistrict.addItem("Anuradhapura");
            cmbDistrict.addItem("Polonnaruwa");
            cmbDistrict.setSelectedIndex(0);

        } else if (cmbProvince.getSelectedItem() == "Central") {
            cmbDistrict.removeAllItems();
            cmbDistrict.addItem("Any");
            cmbDistrict.addItem("Matale");
            cmbDistrict.addItem("Kandy");
            cmbDistrict.addItem("Nuwara Eliya");
            cmbDistrict.setSelectedIndex(0);

        } else if (cmbProvince.getSelectedItem() == "Sabaragamuwa	") {
            cmbDistrict.removeAllItems();
            cmbDistrict.addItem("Any");
            cmbDistrict.addItem("Kegalle");
            cmbDistrict.addItem("Ratnapura");
            cmbDistrict.setSelectedIndex(0);

        } else if (cmbProvince.getSelectedItem() == "Eastern") {
            cmbDistrict.removeAllItems();
            cmbDistrict.addItem("Any");
            cmbDistrict.addItem("Trincomalee");
            cmbDistrict.addItem("Batticaloa");
            cmbDistrict.addItem("Ampara");
            cmbDistrict.setSelectedIndex(0);

        } else if (cmbProvince.getSelectedItem() == "Uva") {
            cmbDistrict.removeAllItems();
            cmbDistrict.addItem("Any");
            cmbDistrict.addItem("Badulla");
            cmbDistrict.addItem("Monaragala");
            cmbDistrict.setSelectedIndex(0);

        } else if (cmbProvince.getSelectedItem() == "Southern") {
            cmbDistrict.removeAllItems();
            cmbDistrict.addItem("Any");
            cmbDistrict.addItem("Hambantota");
            cmbDistrict.addItem("Matara");
            cmbDistrict.addItem("Galle");
            cmbDistrict.setSelectedIndex(0);

        } else {
            cmbDistrict.removeAllItems();
            cmbDistrict.addItem("Any");
            cmbDistrict.setSelectedIndex(0);
        }
    }//GEN-LAST:event_cmbDistrictFocusGained

    private void cmbProvinceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbProvinceFocusLost
        // TODO add your handling code here:
        cmbDistrict.removeAllItems();
        cmbDistrict.addItem("Any");
        cmbDistrict.setSelectedIndex(0);
    }//GEN-LAST:event_cmbProvinceFocusLost

    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectDateRange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectDateRange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectDateRange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectDateRange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SelectDateRange dialog = new SelectDateRange(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox<String> cmbDistrict;
    private javax.swing.JComboBox<String> cmbProvince;
    private javax.swing.JComboBox<String> cmbResult;
    private com.toedter.calendar.JDateChooser dcDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;
}
