/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controler.LoginManagement;
import controler.MessageManagement;
import controler.Validations;
import javax.swing.JOptionPane;
import model.Login;

/**
 *
 * @author lihin
 */
@SuppressWarnings("serial")
public class UserRegisterDialog extends javax.swing.JDialog {

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    /**
     * A return status code - returned if OK button has been pressed
     */
    /**
     * Creates new form UserRegisterDialog
     *
     */
    public UserRegisterDialog() {
        initComponents();
        this.setTitle("REGISTER FORM");
        // Close the dialog when Esc is pressed

    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        pnlRegistraionMainBack = new javax.swing.JPanel();
        lblRegTitle = new javax.swing.JLabel();
        pnlTopHrLine = new javax.swing.JPanel();
        lblTime = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        pnlUserData = new javax.swing.JPanel();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        lblNic = new javax.swing.JLabel();
        txtNic = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        spinAge = new javax.swing.JSpinner();
        lblContact = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        lblWorkRole = new javax.swing.JLabel();
        cmbWorkRole = new javax.swing.JComboBox<>();
        btnNext = new javax.swing.JButton();
        lblWorkRoleId = new javax.swing.JLabel();
        txtWorkRoleId = new javax.swing.JTextField();
        cbInfoConfirmation = new javax.swing.JCheckBox();
        cbPrivacyStatement = new javax.swing.JCheckBox();
        txtUserInfoErr = new javax.swing.JLabel();
        pnlRegistraionCompeteStep = new javax.swing.JPanel();
        btnRegister = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        lblUsername = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        lblCreatePass = new javax.swing.JLabel();
        txtConfPass = new javax.swing.JPasswordField();
        lblConfPass = new javax.swing.JLabel();
        txtCreatePass = new javax.swing.JPasswordField();
        txtRegistrationErr = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlRegistraionMainBack.setBackground(new java.awt.Color(119, 136, 153));
        pnlRegistraionMainBack.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRegTitle.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        lblRegTitle.setForeground(new java.awt.Color(0, 0, 0));
        lblRegTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegTitle.setText("U S E R    R E G I S T R A T I O N     F O R M");
        pnlRegistraionMainBack.add(lblRegTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 20));

        pnlTopHrLine.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnlTopHrLineLayout = new javax.swing.GroupLayout(pnlTopHrLine);
        pnlTopHrLine.setLayout(pnlTopHrLineLayout);
        pnlTopHrLineLayout.setHorizontalGroup(
            pnlTopHrLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        pnlTopHrLineLayout.setVerticalGroup(
            pnlTopHrLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlRegistraionMainBack.add(pnlTopHrLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 650, 1));

        lblTime.setForeground(new java.awt.Color(0, 0, 0));
        lblTime.setText("Time");
        pnlRegistraionMainBack.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 90, 30));

        lblDate.setForeground(new java.awt.Color(0, 0, 0));
        lblDate.setText("Date");
        pnlRegistraionMainBack.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 110, 30));

        pnlUserData.setBackground(new java.awt.Color(119, 136, 153));

        lblFirstName.setForeground(new java.awt.Color(0, 0, 0));
        lblFirstName.setText("First Name       :");

        lblLastName.setForeground(new java.awt.Color(0, 0, 0));
        lblLastName.setText("Last Name        :");

        lblNic.setForeground(new java.awt.Color(0, 0, 0));
        lblNic.setText("NIC No              :");

        lblAge.setForeground(new java.awt.Color(0, 0, 0));
        lblAge.setText("Age                    :");

        lblContact.setForeground(new java.awt.Color(0, 0, 0));
        lblContact.setText("Contact No       :");

        lblAddress.setForeground(new java.awt.Color(0, 0, 0));
        lblAddress.setText("Address             :");

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        jScrollPane3.setViewportView(txtAddress);

        lblWorkRole.setForeground(new java.awt.Color(0, 0, 0));
        lblWorkRole.setText("Work Role         :");

        cmbWorkRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Doctor", "Nurse", "Lab Worker" }));

        btnNext.setBackground(new java.awt.Color(95, 158, 160));
        btnNext.setForeground(new java.awt.Color(0, 0, 0));
        btnNext.setText("Next > >");
        btnNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNextMouseClicked(evt);
            }
        });

        lblWorkRoleId.setForeground(new java.awt.Color(0, 0, 0));
        lblWorkRoleId.setText("roleid");

        cbInfoConfirmation.setForeground(new java.awt.Color(0, 0, 0));
        cbInfoConfirmation.setText("I hereby declare that the information given above is true and accurate to the best of my knowledge.");
        cbInfoConfirmation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbInfoConfirmationActionPerformed(evt);
            }
        });

        cbPrivacyStatement.setForeground(new java.awt.Color(0, 0, 0));
        cbPrivacyStatement.setText("I accept the Privacy Statement");
        cbPrivacyStatement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPrivacyStatementActionPerformed(evt);
            }
        });

        txtUserInfoErr.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        txtUserInfoErr.setForeground(new java.awt.Color(153, 0, 51));
        txtUserInfoErr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlUserDataLayout = new javax.swing.GroupLayout(pnlUserData);
        pnlUserData.setLayout(pnlUserDataLayout);
        pnlUserDataLayout.setHorizontalGroup(
            pnlUserDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserDataLayout.createSequentialGroup()
                .addGroup(pnlUserDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUserDataLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(pnlUserDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlUserDataLayout.createSequentialGroup()
                                .addComponent(lblLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtLastName))
                            .addGroup(pnlUserDataLayout.createSequentialGroup()
                                .addComponent(lblFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFirstName))
                            .addGroup(pnlUserDataLayout.createSequentialGroup()
                                .addGroup(pnlUserDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblNic, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                    .addComponent(lblAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlUserDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNic)
                                    .addGroup(pnlUserDataLayout.createSequentialGroup()
                                        .addComponent(spinAge, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(pnlUserDataLayout.createSequentialGroup()
                                .addComponent(lblContact, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtContact))
                            .addGroup(pnlUserDataLayout.createSequentialGroup()
                                .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane3))
                            .addGroup(pnlUserDataLayout.createSequentialGroup()
                                .addGroup(pnlUserDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlUserDataLayout.createSequentialGroup()
                                        .addGroup(pnlUserDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(lblWorkRoleId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblWorkRole, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(pnlUserDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnNext)
                                            .addComponent(cmbWorkRole, 0, 169, Short.MAX_VALUE)
                                            .addComponent(txtWorkRoleId)))
                                    .addGroup(pnlUserDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(cbPrivacyStatement, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbInfoConfirmation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(0, 57, Short.MAX_VALUE))))
                    .addGroup(pnlUserDataLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtUserInfoErr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlUserDataLayout.setVerticalGroup(
            pnlUserDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtUserInfoErr, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlUserDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFirstName)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlUserDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastName)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlUserDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNic)
                    .addComponent(txtNic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlUserDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAge)
                    .addComponent(spinAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlUserDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContact)
                    .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlUserDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAddress)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(pnlUserDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWorkRole)
                    .addComponent(cmbWorkRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlUserDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWorkRoleId)
                    .addComponent(txtWorkRoleId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(cbInfoConfirmation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbPrivacyStatement)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pnlRegistraionMainBack.add(pnlUserData, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 650, 540));

        pnlRegistraionCompeteStep.setBackground(new java.awt.Color(176, 196, 222));

        btnRegister.setBackground(new java.awt.Color(0, 255, 255));
        btnRegister.setForeground(new java.awt.Color(0, 0, 0));
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        cancelButton.setBackground(new java.awt.Color(238, 130, 238));
        cancelButton.setForeground(new java.awt.Color(0, 0, 0));
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        lblUsername.setForeground(new java.awt.Color(0, 0, 0));
        lblUsername.setText("Username               :");

        txtUserName.setToolTipText("This will be shown on your Dashboard");
        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });

        lblCreatePass.setForeground(new java.awt.Color(0, 0, 0));
        lblCreatePass.setText("Create Password    :");

        lblConfPass.setForeground(new java.awt.Color(0, 0, 0));
        lblConfPass.setText("Confirm Password :");

        txtRegistrationErr.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        txtRegistrationErr.setForeground(new java.awt.Color(204, 0, 0));
        txtRegistrationErr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlRegistraionCompeteStepLayout = new javax.swing.GroupLayout(pnlRegistraionCompeteStep);
        pnlRegistraionCompeteStep.setLayout(pnlRegistraionCompeteStepLayout);
        pnlRegistraionCompeteStepLayout.setHorizontalGroup(
            pnlRegistraionCompeteStepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegistraionCompeteStepLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(pnlRegistraionCompeteStepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblConfPass)
                    .addGroup(pnlRegistraionCompeteStepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblUsername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCreatePass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(pnlRegistraionCompeteStepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegistraionCompeteStepLayout.createSequentialGroup()
                        .addComponent(txtConfPass, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRegister)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(cancelButton))
                    .addGroup(pnlRegistraionCompeteStepLayout.createSequentialGroup()
                        .addGroup(pnlRegistraionCompeteStepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCreatePass, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(35, 35, 35))
            .addGroup(pnlRegistraionCompeteStepLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtRegistrationErr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlRegistraionCompeteStepLayout.setVerticalGroup(
            pnlRegistraionCompeteStepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistraionCompeteStepLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtRegistrationErr, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlRegistraionCompeteStepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlRegistraionCompeteStepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCreatePass)
                    .addComponent(txtCreatePass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlRegistraionCompeteStepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConfPass)
                    .addComponent(txtConfPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegister)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        getRootPane().setDefaultButton(btnRegister);

        pnlRegistraionMainBack.add(pnlRegistraionCompeteStep, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 650, 220));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlRegistraionMainBack.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 830, -1, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRegistraionMainBack, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRegistraionMainBack, javax.swing.GroupLayout.PREFERRED_SIZE, 849, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("deprecation")
    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
            if (txtUserName.getText().length() == 0) {
                txtRegistrationErr.setText("*Create a Username ");
            } else if (Validations.validateUserName(txtUserName.getText())) {
                txtRegistrationErr.setText("*Username can not start with a blank ");
            } else if (Validations.validateUserNamePattern(txtUserName.getText())) {
                txtRegistrationErr.setText("*Username should be more than 3 characters and less than 15 \n Can Only Contain a-z, A-Z, 0-9, points, dashes and underscores. ");
            }/* else if (chkPreviousUsernames.chkPreviousUsernames()==1) {
                lblrRegErr.setText("That Username is Taken Try another one ");
            }*/
            else if(txtCreatePass.getText().length()==0){
                txtRegistrationErr.setText("*Create a Password ");
            }else if(Validations.validatePassword(txtCreatePass.getText())){
               txtRegistrationErr.setText("*Password should be Minimum eight characters Maximum 15,\n And should have at least one uppercase letter,one lowercase letter and one number"); 
            }else if(Validations.validateConfPassMatch(txtCreatePass.getText(),txtConfPass.getText())){
                txtRegistrationErr.setText("*Passwords didnt match ");
            }
            else{
                txtRegistrationErr.setText(" ");
                Login login = new Login(txtUserName.getText(),txtCreatePass.getText(),(txtFirstName.getText()+" "+txtLastName.getText()),txtNic.getText(),(Integer)spinAge.getValue(),txtContact.getText(),txtAddress.getText(),(String)cmbWorkRole.getSelectedItem());
                LoginManagement registerLogin = new LoginManagement(login);   
                registerLogin.registerLogin();
                this.dispose();
               
           
              /* Login login = new Login(txtrName.getText(),txtrNic.getText(),Integer.parseInt(txtrAge.getText()),txtrContact.getText(),txtrAddress.getText(),(String)cmbrRole.getSelectedItem());
               LoginManagement registerUser = new LoginManagement(login);
               registerUser.registerUser();*/
            }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setDefaultCloseOperation(UserRegisterDialog.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_closeDialog

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        pnlRegistraionCompeteStep.setVisible(false);
        cbPrivacyStatement.setVisible(false);
        lblWorkRoleId.setVisible(false);
        txtWorkRoleId.setVisible(false);
        cbInfoConfirmation.setVisible(false);
        txtRegistrationErr.setVisible(false);
        txtUserInfoErr.setVisible(false);


    }//GEN-LAST:event_formWindowOpened

    private void cbInfoConfirmationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbInfoConfirmationActionPerformed
        // TODO add your handling code here:
        if(txtWorkRoleId.getText().length()==0){
          cbInfoConfirmation.setSelected(false);
         JOptionPane.showMessageDialog(MessageManagement.getVisibleContent(), "Input your "+cmbWorkRole.getSelectedItem()+" ID", "Login Details Management ", JOptionPane.INFORMATION_MESSAGE);
        }else {
            cbPrivacyStatement.setVisible(true);
        }
       
    }//GEN-LAST:event_cbInfoConfirmationActionPerformed

    private void btnNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextMouseClicked
        // TODO add your handling code here:

        if (txtFirstName.getText().length() == 0 || txtLastName.getText().length() == 0) {
            txtUserInfoErr.setVisible(true);
            txtUserInfoErr.setText("*First Name or Last Name Cannot be Blank!! ");
        } else if (Validations.validateNoNumSymb(txtFirstName.getText())) {
            txtUserInfoErr.setVisible(true);
            txtUserInfoErr.setText("*First Name or Last Name Name Can not Contain Symbols or Numbers ");

        } else if (txtNic.getText().length() == 0) {
            txtUserInfoErr.setVisible(true);
            txtUserInfoErr.setText("*Id Cannot be Blank!! ");
        } else if (Validations.validateNoSpace(txtNic.getText())) {
            txtUserInfoErr.setVisible(true);
            txtUserInfoErr.setText("*Id No can not contain spaces!! ");
        } /*else if((txtrNic.getText().length()!= 10) && (txtrNic.getText().length()!=12)){
            lblrValidErr.setText("*Invalid ID ");
        }*/ else if (Validations.validateOldId(txtNic.getText()) == Validations.validateNewId(txtNic.getText())) {
            txtUserInfoErr.setVisible(true);
            txtUserInfoErr.setText("*Invalid ID ");
        } /*  else if(Validations.validateId(txtrNic.getText())){
            lblrValidErr.setText("*Invalid ID (old id)");
        }*/ else if (!Validations.validateOnlyNum(spinAge.getValue().toString())) {
            txtUserInfoErr.setVisible(true);
            txtUserInfoErr.setText("*Age should be numeric");
        } else if (spinAge.getValue().toString().length() > 2) {
            txtUserInfoErr.setVisible(true);
            txtUserInfoErr.setText("*Invalid Age");
        } else if (Validations.validateContact(txtContact.getText())) {
            txtUserInfoErr.setVisible(true);
            txtUserInfoErr.setText("*Invalid mobile No");
        } else if (cmbWorkRole.getSelectedIndex() == 0) {
            txtUserInfoErr.setVisible(true);
            txtUserInfoErr.setText("*Select your job Role");
        } else {

            txtUserInfoErr.setText("");
        }
        if (txtUserInfoErr.getText() == "") {
            
            cbInfoConfirmation.setVisible(true);
            lblWorkRoleId.setVisible(true);
            txtWorkRoleId.setVisible(true);
            txtUserInfoErr.setVisible(false);
            //System.out.println(txtUserInfoErr.getText());
        }
        else {
            cbInfoConfirmation.setSelected(false);
            cbInfoConfirmation.setVisible(false);
            cbPrivacyStatement.setSelected(false);
            cbPrivacyStatement.setVisible(false);
        }
            


    }//GEN-LAST:event_btnNextMouseClicked

    private void cbPrivacyStatementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPrivacyStatementActionPerformed
        // TODO add your handling code here:
        if(txtWorkRoleId.getText().length()==0){
          cbInfoConfirmation.setSelected(false);
          cbPrivacyStatement.setSelected(false);
          cbPrivacyStatement.setVisible(false);
         JOptionPane.showMessageDialog(MessageManagement.getVisibleContent(), "Input your "+cmbWorkRole.getSelectedItem()+" ID", "Login Details Management ", JOptionPane.INFORMATION_MESSAGE);
         }else {
            pnlRegistraionCompeteStep.setVisible(true);
        }
        
    }//GEN-LAST:event_cbPrivacyStatementActionPerformed

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserRegisterDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserRegisterDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserRegisterDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserRegisterDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                UserRegisterDialog dialog = new UserRegisterDialog();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton cancelButton;
    private javax.swing.JCheckBox cbInfoConfirmation;
    private javax.swing.JCheckBox cbPrivacyStatement;
    private javax.swing.JComboBox<String> cmbWorkRole;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblConfPass;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblCreatePass;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblNic;
    private javax.swing.JLabel lblRegTitle;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblWorkRole;
    private javax.swing.JLabel lblWorkRoleId;
    private javax.swing.JPanel pnlRegistraionCompeteStep;
    private javax.swing.JPanel pnlRegistraionMainBack;
    private javax.swing.JPanel pnlTopHrLine;
    private javax.swing.JPanel pnlUserData;
    private javax.swing.JSpinner spinAge;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JPasswordField txtConfPass;
    private javax.swing.JTextField txtContact;
    private javax.swing.JPasswordField txtCreatePass;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtNic;
    private javax.swing.JLabel txtRegistrationErr;
    private javax.swing.JLabel txtUserInfoErr;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JTextField txtWorkRoleId;
    // End of variables declaration//GEN-END:variables

    private final int returnStatus = DISPOSE_ON_CLOSE;
}
